#pragma once

enum class eItemList
{
	// Util
	WEAPON_JETPACK,
	WEAPON_LOWGRAVITY,
	WEAPON_FASTWALK,
	WEAPON_LASERSIGHT,
	WEAPON_INVISIBILITY,

	// F1
	WEAPON_BAZOOKA,
	WEAPON_HOMINGMISSILE,
	WEAPON_MORTAR,
	WEAPON_HOMINGPIGEON,
	WEAPON_SHEEPLAUNCHER,

	// F2
	WEAPON_GRENADE,
	WEAPON_CLUSTERBOMB,
	WEAPON_BANNANABOMB,
	WEAPON_BATTLEAXE,
	WEAPON_EARTHQUAKE,

	// F3
	WEAPON_SHOTGUN,
	WEAPON_HANDGUN,
	WEAPON_UZI,
	WEAPON_MINIGUN,
	WEAPON_LONGBOW,

	// F4
	WEAPON_FIREPUNCH,
	WEAPON_DRAGONBALL,
	WEAPON_KAMIKAZE,
	WEAPON_SUICIDEBOMBER,
	WEAPON_PROD,

	// F5
	WEAPON_DYNAMITE,
	WEAPON_MINE,
	WEAPON_SHEEP,
	WEAPON_SUPERSHEEP,
	WEAPON_MOLEBOMB,

	// F6
	WEAPON_AIRSTRIKE,
	WEAPON_NAPALMSTRIKE,
	WEAPON_MAILSTRIKE,
	WEAPON_MINESTRIKE,
	WEAPON_MOLESQUADRON,

	// F7
	WEAPON_BLOWTORCH,
	WEAPON_PNEUMATICDRILL,
	WEAPON_GIRDER,
	WEAPON_BASEBALLBAT,
	WEAPON_GIRDERSTARTERPACK,

	// F8
	WEAPON_NINJAROPE,
	WEAPON_BUNGEE,
	WEAPON_PARACHUTE,
	WEAPON_TELEPORT,
	WEAPON_SCALESOFJUSTICE,

	// F9
	WEAPON_SUPERBANANABOMB,
	WEAPON_HOLYHANDGRENDADE,
	WEAPON_FLAMETHROWER,
	WEAPON_SALVATIONARMY,
	WEAPON_MBBOMB,

	// F10
	WEAPON_PETROLBOMB,
	WEAPON_SKUNK,
	WEAPON_PRICELESSMINGVASE,
	WEAPON_FRENCHSHEEPSTRIKE,
	WEAPON_MIKESCARPETBOMB,

	// F11
	WEAPON_MADCOWS,
	WEAPON_OLDWOMAN,
	WEAPON_CONCREATEDONKEY,
	WEAPON_INDIANNUCLEAR,
	WEAPON_ARMAGEDDON,

	// F12
	WEAPON_SKIPGO,
	WEAPON_SURRENDER,
	WEAPON_SELECTWORM,
	WEAPON_FREEZE,
	WEAPON_PATSYSMAGICBULLET,

	MAX
};
